export const PLAN_IDS = {
  FREE: 'free',
  BASIC: 'basic',
  PRO: 'pro',
  PREMIUM: 'premium',
};

export const PLAN_RANK = {
  free: 0,
  basic: 1,
  pro: 2,
  premium: 3,
};

export const PLANS_CONFIG = {
  free: {
    id: 'free',
    label: 'Grátis',
    color: 'gray',
    price: 'R$ 0/mês',
    badge: '⬜ Grátis',
    adLimit: 1,
    categoryLimit: 1,
    photoLimit: 0,
    hasSocialLinks: false,
    hasStats: false,
    hasFeaturedBadge: false,
    hasTopSearch: false,
    hasBanner: false,
    hasVerifiedBadge: false,
    hasReports: false,
    hasCampaigns: false,
  },
  basic: {
    id: 'basic',
    label: 'Básico',
    color: 'blue',
    price: 'R$ 19,90/mês',
    badge: '🔵 Básico',
    adLimit: 3,
    categoryLimit: 1,
    photoLimit: 0,
    hasSocialLinks: false,
    hasStats: false,
    hasFeaturedBadge: false,
    hasTopSearch: false,
    hasBanner: false,
    hasVerifiedBadge: false,
    hasReports: false,
    hasCampaigns: false,
  },
  pro: {
    id: 'pro',
    label: 'Pro',
    color: 'emerald',
    price: 'R$ 39,90/mês',
    badge: '🟢 Pro',
    adLimit: 999,
    categoryLimit: 3,
    photoLimit: 10,
    hasSocialLinks: true,
    hasStats: true,
    hasFeaturedBadge: true,
    hasTopSearch: false,
    hasBanner: false,
    hasVerifiedBadge: false,
    hasReports: false,
    hasCampaigns: false,
  },
  premium: {
    id: 'premium',
    label: 'Premium',
    color: 'amber',
    price: 'R$ 79,90/mês',
    badge: '👑 Premium',
    adLimit: 999,
    categoryLimit: 999,
    photoLimit: 999,
    hasSocialLinks: true,
    hasStats: true,
    hasFeaturedBadge: true,
    hasTopSearch: true,
    hasBanner: true,
    hasVerifiedBadge: true,
    hasReports: true,
    hasCampaigns: true,
  },
};

export function hasPlanAccess(currentPlan, requiredPlan) {
  return (PLAN_RANK[currentPlan] ?? 0) >= (PLAN_RANK[requiredPlan] ?? 0);
}
