#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

# This hook will validate the commit messages according to the conventional commit format

commit_msg_regex='^([a-z]+)(\(([^)]+)\))?: [ A-Z].*$'

if ! grep -qE "$commit_msg_regex" "$1"; then
  echo 'Error: Commit message does not follow the conventional commit format.'
  echo 'Please use the format: <type>(<scope>): <subject>'
  exit 1
}